// Types are fully generated by `npx convex dev`
/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  userProfiles: defineTable({
    deviceId: v.string(),
    challengeStartDate: v.union(v.string(), v.null()),
    onboardingCompleted: v.boolean(),
  }).index("by_deviceId", ["deviceId"]),

  dailyEntries: defineTable({
    deviceId: v.string(),
    date: v.string(),
    rituals: v.record(v.string(), v.boolean()),
    reflection: v.union(
      v.literal("wave"),
      v.literal("building-swell"),
      v.literal("tsunami"),
      v.null(),
    ),
    mood: v.union(
      v.literal("calm"),
      v.literal("steady"),
      v.literal("energised"),
      v.literal("tired"),
      v.literal("overwhelmed"),
      v.null(),
    ),
    isComplete: v.boolean(),
    isPartial: v.boolean(),
  })
    .index("by_deviceId", ["deviceId"])
    .index("by_deviceId_date", ["deviceId", "date"]),
});
