// Types are fully generated by `npx convex dev`
/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck
import { v } from "convex/values";
import { mutation, query } from "./_generated/server";

export const getProfile = query({
  args: { deviceId: v.string() },
  handler: async (ctx, { deviceId }) => {
    return await ctx.db
      .query("userProfiles")
      .withIndex("by_deviceId", (q) => q.eq("deviceId", deviceId))
      .unique();
  },
});

export const upsertProfile = mutation({
  args: {
    deviceId: v.string(),
    challengeStartDate: v.union(v.string(), v.null()),
    onboardingCompleted: v.boolean(),
    challengeReflectionViewed: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    const existing = await ctx.db
      .query("userProfiles")
      .withIndex("by_deviceId", (q) => q.eq("deviceId", args.deviceId))
      .unique();

    if (existing) {
      await ctx.db.patch(existing._id, {
        challengeStartDate: args.challengeStartDate,
        onboardingCompleted: args.onboardingCompleted,
        challengeReflectionViewed: args.challengeReflectionViewed ?? false,
      });
      return existing._id;
    }

    return await ctx.db.insert("userProfiles", {
      ...args,
      challengeReflectionViewed: args.challengeReflectionViewed ?? false,
    });
  },
});

export const getDailyEntries = query({
  args: { deviceId: v.string() },
  handler: async (ctx, { deviceId }) => {
    return await ctx.db
      .query("dailyEntries")
      .withIndex("by_deviceId", (q) => q.eq("deviceId", deviceId))
      .collect();
  },
});

export const getDailyEntry = query({
  args: { deviceId: v.string(), date: v.string() },
  handler: async (ctx, { deviceId, date }) => {
    return await ctx.db
      .query("dailyEntries")
      .withIndex("by_deviceId_date", (q) =>
        q.eq("deviceId", deviceId).eq("date", date),
      )
      .unique();
  },
});

export const upsertDailyEntry = mutation({
  args: {
    deviceId: v.string(),
    date: v.string(),
    rituals: v.record(v.string(), v.boolean()),
    reflection: v.union(
      v.literal("wave"),
      v.literal("building-swell"),
      v.literal("tsunami"),
      v.null(),
    ),
    mood: v.union(
      v.literal("calm"),
      v.literal("steady"),
      v.literal("energised"),
      v.literal("tired"),
      v.literal("overwhelmed"),
      v.null(),
    ),
    isComplete: v.boolean(),
    isPartial: v.boolean(),
  },
  handler: async (ctx, args) => {
    const existing = await ctx.db
      .query("dailyEntries")
      .withIndex("by_deviceId_date", (q) =>
        q.eq("deviceId", args.deviceId).eq("date", args.date),
      )
      .unique();

    if (existing) {
      await ctx.db.patch(existing._id, {
        rituals: args.rituals,
        reflection: args.reflection,
        mood: args.mood,
        isComplete: args.isComplete,
        isPartial: args.isPartial,
      });
      return existing._id;
    }

    return await ctx.db.insert("dailyEntries", args);
  },
});
